name: 'dbt_'
version: '1.0.0'

profile: 'dbt_'

model-paths: ["models"]
test-paths: ["tests"]
# analysis-paths: ["analyses"]
# seed-paths: ["seeds"]
macro-paths: ["macros"]
# snapshot-paths: ["snapshots"]

# directories to be removed by `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

# https://docs.getdbt.com/docs/configuring-models
models:
  dbt_:
    +materialized: table
